### Site metadata

title: Artist's Portfolio
description: A gallery of images for an artist's portfolio, built with Jekyll

url: "https://noradubost.github.io"
baseurl: ""

github_username: "noradubost"
repository: "noradubost/noradubost.github.io"

google_analytics_key: ""

# For SEO tag.
logo: /siteicon.png
author:
  name: Nora Dubost
  twitter:
social:
  name: Nora's Portfolio
  links:
    - https://github.com/noradubost/noradubost.github.io

### Build settings

timezone: Etc/UTC

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      text_width: true
  - scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - LICENCE-source
  - Makefile
  - netlify.toml
